services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/webapp

  back:
    build: ./back
    restart: unless-stopped
    ports:
      - 4001:4000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - THEGOODCORNER_DBPASS=${DBPASS}
    volumes:
      - ./back:/app

  db:
    image: postgres:16
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_PASSWORD=${DBPASS_ADMIN}
    ports:
      - 5433:5432
    volumes:
      - ../the-good-corner-db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
